name = "Bulmin"
license = "MIT"
licenselink = "https://github.com/tehuel/bulmin/blob/master/LICENSE"
description = "Minimal Blog Theme, using Bulma CSS"
homepage = "https://tehuel.github.io/bulmin/"
tags = ["blog", "responsive"]
features = ["blog", "responsive"]
min_version = "0.37.1"

[author]
  name = "Tehuel Torres Baldi"
  homepage = "https://tehuel.blog"
